var url = null

const editor = ace.edit('editor') //takes HTML id of element we want to make a code editor as an argument
editor.setTheme('ace/theme/pastel_on_dark') //sets theme of editor
editor.getSession().setMode('ace/mode/html') //sets editor mode to html

//take HTML Blob as argument, will return object url of it
function createUrl(html) {
    var blob = new Blob([html], { type: 'text/html' })
    return URL.createObjectURL(blob)
  }
  
//takes a url generated by createurl as argument, deletes it 
function removeUrl(url) {
    URL.revokeObjectURL(url)
    console.log('Revoked URL')
  }
  
//return our iframe object from Document Object Model
function getIframe() {
    var iframe = document.getElementById('iframe')
    return iframe
  }
  
//take URL as argument and will set iframe's src attribute to this URL
function setIframeUrl(url) {
    var iframe = getIframe()
    iframe.src = url
  }
  
//return the code of our editor
function getEditorCode() {
    return editor.getValue()
  }
  
function buttonclick() {
  var code = getEditorCode()
  removeUrl(url)
  url = createUrl(code)
  setIframeUrl(url)
}
